version: 4.0.{build}

build_script:
 - cmd: gem sources -r https://rubygems.org/
 - cmd: gem install bundler --no-ri --no-rdoc --source https://rubygems.org/
 - cmd: bundle install
 - cmd: bundle exec rake
 
artifacts:
 - path: build\pkg\*.nupkg 

test:  off

nuget:
  project_feed: true
